# Generated by Django 2.0 on 2025-03-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegister_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='detection_ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Pesticide_Poisoning_Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.CharField(max_length=3000)),
                ('Years_of_Exposure', models.CharField(max_length=3000)),
                ('Number_of_Symptoms', models.CharField(max_length=3000)),
                ('Protective_Gear_Usage', models.CharField(max_length=3000)),
                ('Work_Hours_per_Day', models.CharField(max_length=3000)),
                ('Proximity_to_Pesticide_Storage', models.CharField(max_length=3000)),
                ('Gender', models.CharField(max_length=3000)),
                ('Pesticide_Type', models.CharField(max_length=3000)),
                ('Location', models.CharField(max_length=3000)),
                ('Symptoms', models.CharField(max_length=3000)),
                ('Pesticide_Contact', models.CharField(max_length=3000)),
                ('Prediction', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Pesticide_Poisoning_Diagnosis_accuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
    ]
